### PR TITLE
Typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
That's a lot of changes. Would you be willing to merge them, especially in a single  merge request?

I think most typos occur in codes comments, but some of them occur in the documentation and user visible text.

**Comment by gllmflndn** [comment]
Thank you so much @DimitriPapadopoulos ! These are more typos than I expected, good to have them fixed (and thanks to [codespell](https://github.com/codespell-project/codespell)).

While the vast majority of the changes look good to me, I can see some issues, e.g. in `spm_est_smoothness.,m`, `dum` variable being replaced by `dumb` (I would keep it unchanged. It was for `dummy`), `cant` replaced by `can't'` instead of `cannot`. Also OK with `coordinate` even if `co-ordinate' is valid spelling.
These are a lot of files to go through: do you have a recommendation for me of how I can go through all the changes and decide what to do for each and every one of them?

When this has been reviewed, I will be happy to squash and merge - I would actually apply a single patch on the development version (hoping there are not too many conflicts) and everything will then be (soon) available [here](https://github.com/spm/spm/).

**Comment by DimitriPapadopoulos** [comment]
I haven't reviewed the changes thoroughly - I wasn't certain you would be fine with such an invasive merge request.
If you're OK with them, I'll review them once again.

**Comment by DimitriPapadopoulos** [comment]
Indeed, co-ordinate is a valid alternative in some European dictionaries ([Cambridge](https://dictionary.cambridge.org/fr/dictionnaire/anglais/coordinate), [Oxford](https://www.oxfordlearnersdictionaries.com/definition/english/coordinate_2) or [Colllins](https://www.collinsdictionary.com/dictionary/english/coordinate)), but American dictionaries only refer to coordinate only ([Merriam-Webster](https://www.merriam-webster.com/dictionary/coordinate) or the [American Heritage dictionary](https://ahdictionary.com/word/search.html?q=coordinate)). Perhaps it's best to settle for coordinate, unless it makes for too many changes.

**Comment by DimitriPapadopoulos** [comment]
I don't really have a recommendation to review the changes. I'm afraid t's an annoying merge request, with lots of small changes in lots of small files. Perhaps you can review each commit separately. Each commit focuses on a folder. Not sure this helps you.

**Comment by DimitriPapadopoulos** [comment]
Not sure about this one:
`smaple of hyperparameters from thier posterioir p(h|YY,X,Q)`

Can you help?

**Comment by DimitriPapadopoulos** [comment]
I think the rest is good to go. Can you have a look?

**Comment by gllmflndn** [comment]
Thank you. I went through the suggestions, kept 99% of them, merged them with the current development version and pushed them in `r8183`. They will soon be available in another repo hosted here.
This was indeed a rather invasive merge and I hope it will not generate too many conflicts with the other developers...

Thank you!

**Pull request closed without merging**
